name: Remote Deploy via SSH

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to deploy (e.g. main, develop, feature/x)'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            set -e
            cd /var/www/dev-instream/instream

            BRANCH="${{ github.event.inputs.branch }}"

            echo "Running: git fetch and pull"
            git fetch
            git checkout "$BRANCH"
            git pull origin "$BRANCH"

            echo "Pulling backend"
            cd backend || { echo "backend does not exist"; exit 1; }
            git fetch
            git checkout "$BRANCH"
            git pull origin "$BRANCH"

            echo "Pulling frontend"
            cd ..
            cd frontend || { echo "frontend does not exist"; exit 1; }
            git fetch
            git checkout "$BRANCH"
            git pull origin "$BRANCH"

            echo "Returning to root"
            cd ..

            echo "Stopping containers"
            docker compose down

            echo "Building Docker containers (no cache)"
            docker compose build --no-cache

            echo "Starting containers"
            docker compose up -d

            echo "Cleaning up images and builds"
            docker image prune -f && docker builder prune -f
            echo "✅ Deployment completed successfully"
          EOF
