name: Test Docker Build & Push with .env

on:
  push:
    branches:
      - test-cicd  # Change this to your test branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jaylinearloop/nodejswebapp1  # change this to your Docker Hub repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write .env file from secret
        run: |
          echo "${TEST_ENV}" > .env
          echo ".env file contents:"
          cat .env
        shell: bash
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:test-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest-test
